// Mock data for hotels and restaurants

import type { Hotel, Restaurant } from "./types"

export const mockHotels: Hotel[] = [
  {
    id: "hotel-1",
    name: "Grand Plaza Hotel",
    location: "Downtown",
    rating: 4.8,
    reviews: 324,
    image: "/luxury-hotel-lobby-chandelier.png",
    description: "Experience luxury and comfort at our 5-star hotel in the heart of the city.",
    amenities: ["WiFi", "Pool", "Gym", "Restaurant", "Spa", "Parking"],
    pricePerNight: 250,
  },
  {
    id: "hotel-2",
    name: "Riverside Inn",
    location: "Waterfront",
    rating: 4.5,
    reviews: 218,
    image: "/modern-riverside-hotel-with-river-view.jpg",
    description: "Enjoy stunning river views and modern amenities.",
    amenities: ["WiFi", "Restaurant", "Bar", "Business Center", "Room Service"],
    pricePerNight: 180,
  },
  {
    id: "hotel-3",
    name: "Cozy Downtown Lodge",
    location: "City Center",
    rating: 4.3,
    reviews: 156,
    image: "/cozy-boutique-hotel-entrance.jpg",
    description: "A charming boutique hotel perfect for business and leisure travelers.",
    amenities: ["WiFi", "Breakfast", "Bar", "Gym", "Meeting Rooms"],
    pricePerNight: 120,
  },
  {
    id: "hotel-4",
    name: "Mountain Peak Resort",
    location: "Highlands",
    rating: 4.7,
    reviews: 412,
    image: "/luxury-mountain-resort-snow-peaks-view.jpg",
    description: "Spectacular mountain views and world-class amenities.",
    amenities: ["WiFi", "Ski Resort", "Spa", "Restaurant", "Heated Pool", "Concierge"],
    pricePerNight: 350,
  },
]

export const mockRestaurants: Restaurant[] = [
  {
    id: "rest-1",
    name: "La Bella Italia",
    location: "Downtown",
    rating: 4.9,
    reviews: 287,
    image: "/italian-restaurant-elegant-dining-room.jpg",
    cuisine: "Italian",
    priceRange: "$$$",
    description: "Authentic Italian cuisine with handmade pasta and fine wines.",
    workingHours: "11:00 AM - 11:00 PM",
  },
  {
    id: "rest-2",
    name: "Sakura Sushi Bar",
    location: "Arts District",
    rating: 4.7,
    reviews: 195,
    image: "/modern-sushi-restaurant-with-sushi-bar.jpg",
    cuisine: "Japanese",
    priceRange: "$$",
    description: "Fresh sushi and contemporary Japanese cuisine.",
    workingHours: "12:00 PM - 10:00 PM",
  },
  {
    id: "rest-3",
    name: "The Grill House",
    location: "Uptown",
    rating: 4.6,
    reviews: 342,
    image: "/steakhouse-upscale-dining-steaks.jpg",
    cuisine: "Steakhouse",
    priceRange: "$$$",
    description: "Premium cuts and classic steakhouse experience.",
    workingHours: "5:00 PM - 11:30 PM",
  },
  {
    id: "rest-4",
    name: "Spice Route",
    location: "Cultural Quarter",
    rating: 4.5,
    reviews: 156,
    image: "/indian-restaurant-curry-dishes-colorful-spices.jpg",
    cuisine: "Indian",
    priceRange: "$$",
    description: "Authentic Indian flavors and aromatic spices.",
    workingHours: "11:30 AM - 10:00 PM",
  },
]
